import Image from './components/product/image/p1.png'
export const data=[
    {   id:0,
        title:"Popular show trend One",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:299.9,
        image:Image,
        rating:3,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:1,
        title:"Popular show trend Two",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:456.9,
        image:"https://www.pngall.com/wp-content/uploads/5/Men-Shoes-PNG-Image-File.png",
        rating:4,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:2,
        title:"Popular show trend Three",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:99.9,
        image:"https://www.pngarts.com/files/2/Shoes-PNG-Free-Download.png",
        rating:2,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:3,
        title:"Popular show trend Four",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:150.9,
        image:"https://www.freeiconspng.com/thumbs/shoes-png/running-shoes-png-sneakers-23.png",
        rating:3,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:4,
        title:"Popular show trend Five",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:700.9,
        image:"https://www.freepnglogos.com/uploads/shoes-png/find-your-perfect-running-shoes-26.png",
        rating:2,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:5,
        title:"Popular show trend Six",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:500.9,
        image:"https://www.pngmart.com/files/6/Shoe-PNG-Photo.png",
        rating:1,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:6,
        title:"Popular show trend Seven",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"ASIAN Men's Bouncer-01 Sports,Walking,Gym",
        price:350.9,
        image:"https://i.pinimg.com/originals/34/86/54/348654cc9b185bcccbeea80d2fae2bf8.png",
        rating:4,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
    {   id:7,
        title:"Popular show trend Eight",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:290.9,
        image:"https://www.freeiconspng.com/thumbs/shoes-png/green-asics-running-shoes-png-image-4.png",
        rating:4,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42]
    },
    {   id:8,
        title:"Popular show trend Nine",
        desc:"Nike Air max270 to chunk Taylors",
        descLong:"Nike's Air Force 1s were among the most popular sneakers this year",
        price:999.9,
        image:"https://www.pngall.com/wp-content/uploads/5/Sylish-Men-Shoes-PNG.png",
        rating:4,
        color:["lightblue","red","orange","gray"],
        size:[38,39,40,42,]
    },
]